### ISSUE TITLE
A few requests

### ISSUE THREAD

**Issue by Darkhax** [dries007/curseMeta#1]
Hello, I've been looking into using this for MMD's curse info bot. Basically you give the bot a username, it will tell you how many downloads that user has, and link to their top 10 projects. I was wondering if you could add a few things to help us out. 

This is what the current output looks like. 
![image](https://user-images.githubusercontent.com/2250798/30006842-4c70e6fa-90bf-11e7-95f9-28c67c2a0c22.png)

The main thing missing is the monthly downloads data for a specific project. Im not sure if you have that data available when you scrape it, but it would be nice to keep that feature. Some other feature requests would be a way to get all of the projects from a username. Grabbing the mods.json every few hours and processing it ourselves would allow for this, however it would make the bot less ram/storage efficient than it is now. I noticed that you can [search using a username](https://cursemeta.dries007.net/search#mods-275343) but scraping this has similar performance to what we have now. 

Another thing we have been planning to implement, is a system that will announce when a new mod has been put on Curse. This is probably beyond your scope, but do you think it would be possible to have a way to get all mods that were created since the last time the data was scraped? 

Thanks

**Comment by dries007** [comment]
Hi!
First, cool bot! I need to try it :)

I don't have monthly DL stats, because it's not included in the Curse backend API I use (I'll check to make sure though).
Don't automatically access the search Page, it's all client side JS.
Since all the data is served as static files, no processing is done on the server. (Unless a file is missing.)

For new projects I'd look at the index.json file, it has a list of projectIDs. If you fetch once an hour or so you can diff the lists. (Of skip diffing if the timestamp hasn't changed yet.)

I'm looking into providing some sort of a stats website myself, but that's all optional extra at this point.

**Comment by DeadSix27** [comment]
Sorry for hijacking this issue, but it seemed overdoing it to open an issue just for this short question which is at least somewhat fitting into this issue

@dries007 How exactly do you generate mods.json? 
EDIT: Hours of research to finally find your project and the urls here:
```
http://clientupdate-v6.cursecdn.com/feed/addons/432/v10/complete.json.bz2
http://clientupdate-v6.cursecdn.com/feed/addons/432/v10/hourly.json.bz2
```
That's all I needed. :)
How exactly did you find those urls? I tried going through network requests by the curse app but never found this one, I found the c# addonservice but I have no experience in svcutil stuff.. and looking now at it with JSON files being available. why would you even need that.

Thanks a lot for finding this :) Saves me a ton of time.

**Comment by dries007** [comment]
NikkyAI found them, via wiresharking the Twitch app I believe. I adapted the alpacka-meta project to run better on my platform / with my constraints.

Those urls come with some serious drawbacks, which is why I (and the people using CurseMeta) needed the extra fluff of a webservice.

**Comment by DeadSix27** [comment]
I wiresharked the twitch app too, just couldn't spot that link, but ye I do not have very much experience with wireshark either.

What drawbacks? The size?

**Comment by dries007** [comment]
The size and limited inclusion of vital data (missing files).
If you don't mind me asking, what are you needing them for?

**Comment by DeadSix27** [comment]
@dries007 Writing a python lib based on them, mostly for personal use, but probably will put it on GH too, if I do not forget.

I saw your API but its too much for what I need it for and of course requires your server.

I want the lib to just require the official json of curse (which I'll just add auto-updating functions for.)
