### ISSUE TITLE
docs for GetRepositoryMatchFromSlug

### ISSUE THREAD

**Issue by fiws** [dries007/curseMeta#10]
Pretty basic use-case of resolving a slug to an mod id. No idea how to get it to work.

I tried `minecraft/storage-drawers` using GET & POST in various different forms, but I always just get 200 `null` back (yay)

**Comment by dries007** [comment]
I have no idea how it works actually...

**Comment by TOLoneWolf** [comment]
https://cursemeta.dries007.net/api/v2/direct/GetRepositoryMatchFromSlug/mc/storage-drawers

can find the id for the gameSlug in `AppData\Roaming\Curse Client\Databases\Games.json`
