### ISSUE TITLE
Server is down

### ISSUE THREAD

**Issue by peterix** [dries007/curseMeta#12]
Apparently something super bad happened and the server is responding with internal errors:
https://cursemeta.dries007.net/

See: https://github.com/MultiMC/MultiMC5/issues/2283

**Comment by dries007** [comment]
Fixed for now. MultiMC should work again.

**Comment by BloodWorkXGaming** [comment]
Sorry for bothering, but any update on this?
[This server installer script](https://github.com/AllTheMods/ServerStarter) I wrote also depends on this handy project and is not working due to those changes (or due to the curse bugs).

**Comment by dries007** [comment]
If you only need the projectid-fileid to file resolving, you can use the legacy URL MultiMC uses, `https://cursemeta.dries007.net/<projectid>/<fileid>.json`. I can't update properly at the moment due to exams.

**Comment by BloodWorkXGaming** [comment]
Awesome! Thank you!

Dries <notifications@github.com> schrieb am Sa., 26. Mai 2018, 00:33:
