### ISSUE TITLE
Returned metadata does not contain mod type and intended location anymore

### ISSUE THREAD

**Issue by peterix** [dries007/curseMeta#13]
This leads to issues like these:
https://github.com/MultiMC/MultiMC5/issues/2340#issuecomment-405099776

Specific request:
https://cursemeta.dries007.net/278645/2514913.json

It should contain something like this to be usable:
```
"_Project": {
    "PackageType": "singlefile",
    "Path": "resourcepacks"
},
```

**Comment by dries007** [comment]
The `_` fields where always optional, but I'll re-add them for you :)

Op zo 15 jul. 2018 21:59 schreef Petr Mrázek <notifications@github.com>:

**Comment by peterix** [comment]
Cool.
They are absolutely required for this to be usable for its intended purpose `~_~`
