### ISSUE TITLE
CORS blocks use in front-end web apps.

### ISSUE THREAD

**Issue by Darkhax** [dries007/curseMeta#14]
The CORS settings for https://staging_cursemeta.dries007.net prevent accessing the API from other domains in a browser. This makes it not possible to use the CurseMeta API in a front-end web app.

**Comment by dries007** [comment]
Ah yes, I forgot about that.
I'll try fix it tonight if I remember.

Op do 28 mrt. 2019 19:06 schreef Tyler Hancock <notifications@github.com>:

**Comment by dries007** [comment]
Should be fixed now.
