### ISSUE TITLE
Getting 404 on a mod that should work

### ISSUE THREAD

**Issue by Martmists-GH** [dries007/curseMeta#15]
Link: https://cursemeta.dries007.net/293425/2697986.json

Project: https://minecraft.curseforge.com/projects/alchemistry

File: https://minecraft.curseforge.com/projects/alchemistry/files/2697986

This URL was requested by multimc, and this issue has made it fail to download/install a pack I'm working on.

**Comment by Martmists-GH** [comment]
Also able to replicate with mekanism: https://cursemeta.dries007.net/268560/2698323.json

**Comment by dries007** [comment]
The first URL now no longer 404s. I'm going to assume that was also a file that has not yet synced to the curse API. (It takes about an hour I was told once.)

**Comment by Martmists-GH** [comment]
Why does it take an hour when the file is already available? https://minecraft.curseforge.com/projects/mekanism/files/2698323 resolves fine for me and CurseMeta should be able to fetch data just fine.

**Comment by dries007** [comment]
Because that's how the API works I guess? Ask the curse people. CurseMeta is just a translation layer between the two.
It's possible this is a caching problem, but I don't think non-OK replies are cached.

**Comment by Martmists-GH** [comment]
Is it possible to make CurseMeta scrape when the file exists but isn't up on the official API yet, and cache that result?

**Comment by dries007** [comment]
No. Scraping is not allowed.

**Comment by Martmists-GH** [comment]
Is there any place I can request this to be faster on the official API? There's no easy way to fix this on our end and it basically means I need to wait up to an hour to test my pack :/

**Comment by dries007** [comment]
Not that I'm aware of. I'll look into the caching, but I don't think it's the issue.
I'll update if I find anything, I'll try to have a look today, but no promises.

**Comment by NielsPilgaard** [comment]
This issue is occuring with Quark, specifically https://minecraft.curseforge.com/projects/quark/files/2711580
It has been available for 6 days, so it's not a timing issue.

**Comment by dries007** [comment]
There is an issue with the login API. It changed and I unfortunately don't
really have the time to fix it unless someone else does the reverse
engineering.
I'm in my last week before my thesis deadline.

Op di 21 mei 2019 om 19:18 schreef Niels Pilgaard Grøndahl <
notifications@github.com>:

**Comment by NielsPilgaard** [comment]
Fair enough, good luck with your thesis :)

**Comment by dries007** [comment]
This issue has since been fixed.

**Comment by NielsPilgaard** [comment]
Thank you :)
