### ISSUE TITLE
522s on some project/mod id combinations

### ISSUE THREAD

**Issue by chloeruka** [dries007/curseMeta#22]
Some Project+FileID combinations MultiMC is trying to resolve via CurseMeta are returning host errors. It looks like it might be an intermittent issue, my guess is that the result sometimes manages to make it to the cache but that the backend requests are timing out. Sorry for hammering the heck out of the server 😅 

Examples
* https://cursemeta.dries007.net/242436/3738133.json
* https://cursemeta.dries007.net/245211/3751424.json
* https://cursemeta.dries007.net/377448/3581611.json
* https://cursemeta.dries007.net/401955/3742705.json

![image](https://user-images.githubusercontent.com/30171259/163519737-3b17dd52-ed01-4ea7-b795-5415e3ed362e.png)

**Comment by dries007** [comment]
Server problems happened for about 4  hours. Should be back up now.
