### ISSUE TITLE
Invalid author URL

### ISSUE THREAD

**Issue by Darkhax** [dries007/curseMeta#3]
I noticed that the user profile has the ASPX extension appended when it shouldn't. This is easy to fix on the receiving end, but still a bit weird. 
```
  "Authors": [
    {
      "Name": "NuclearHex",
      "Url": "https://mods.curse.com/members/NuclearHex.aspx"
    }
  ],
```

**Comment by dries007** [comment]
I don't want to change it and cause inconsistencies, but I'll look at the C# code to make sure it isn't being introduced there. If not, then I guess Curse also strips out that extension on the client side.

**Comment by dries007** [comment]
See #9
