### ISSUE TITLE
GameVesion

### ISSUE THREAD

**Issue by Darkhax** [dries007/curseMeta#6]
The game version for releases is is missing an R in the key. Just spent a good amount of time trying to work out why I kept getting issues with undefined values lol. 

```
		{
			"FileType": "release",
			"GameVesion": "1.4.2",
			"ProjectFileID": 642755
		},
```

**Comment by dries007** [comment]
It's that way in the Curse API specification, and it's already part of the API. I can't change it now without breaking things, and adding the key again would just add extra bandwidth.
