### ISSUE TITLE
Site data does not seem to have been updated since 23-Feb-2018

### ISSUE THREAD

**Issue by cjo9900** [dries007/curseMeta#8]
This is causing MultiMC to fail as newer files are not found, causing download failures/json parsing failures.

Last entry in 
https://cursemeta.dries007.net/history/index.json

  "timestamp_human": "2018-02-23 21:58:27 UTC",
  "timestamp": 1519423107,
  "history": [
....    
    1519419991,
    1519423107
  ]
}

So something may need kicking or Curse changed something again.

**Comment by dries007** [comment]
See issue #7

Op 4 mrt. 2018 18:27 schreef "cjo9900" <notifications@github.com>:

**Comment by dries007** [comment]
See #9
