### ISSUE TITLE
CurseMeta v2 updates/todo list

### ISSUE THREAD

**Issue by dries007** [dries007/curseMeta#9]
_You can watch this issue if you want to know if/when sections are finished._

**V2 is now live, under beta label.** A live-edit staging environment can also be found on [staging_cursemeta.dries007.net](https://staging_cursemeta.dries007.net/).

With the v2 python rewrite, all the previous aggregation/stats/history functionality was lost.
Bringing all of it back will take time, but will be done over time.

Feel free to comment and note what you need. New functionality may also be requested here.

# ToDo snapshot as of March 14th
- Referral link: https://workflowy.com/invite/4dfc7739.lnx (Gives me more free space to add stuff!)
- Keep historic DL counts
  - PopularityScores?
  - The sooner the better, less data loss
  - I have the historic data still (Write import script)
  - API
    - Diff downloads (from-to timestamp)
    - Get total downloads per game/type
  - Keep up to date with feeds only?
  - Fixed interval data points or detect a change on every update?
    - I think more fixed interval, probably less data. Maybe even only do changed data?
- Status page
  - Internal statistics such as 
    - Threads running (?)
    - Uptime global/thread (?)
    - Requests served global/thread (?)
    - Task queue size
    - Server load
    - Approx bandwidth used
  - Any other stats?
  - Should this be public?
- Web UI
  - Preferably pretty version of the old thing
    "https://cursemeta2.dries007.net/search.html#mods-287538"
  - Per game, obviously.
  - Per category too, or allow selection of that? (mod, pack, world, addon, ...)
  - Per game version
  - Proper 'fuzzy' search! (partial client side maybe?)
- DB query API
  - Direct or Post processed output?
  - Options
    - GraphQL http://graphql.org/
      " http://docs.graphene-python.org/projects/sqlalchemy/en/latest/tutorial/"
      - Pro: Big, known & supported
    - Flask-Restless (https://flask-restless.readthedocs.io/en/stable/searchformat.html)
      - Pro: Direct integration with DB models
      - Con: Relies on internal DB structure
  - File Download Endpoint (redirect?) https://gist.github.com/NikkyAI/ce29d9ca12fee410c91add7b17bba31a
- Uniform output API (Post process everything)
  - Fix typos (GameVersion is missing the R in some places)
  - Add Addon data to File objects (so less requests are needed)
  - Selective return data
    - Jenkins API like ?
  - Re-processed (or similar but DIY) raw feeds, preferably compressed.
- Statistics pages (Graphs & tables!)
  - Old version: https://cursemeta2.dries007.net/stats/graphs.html
  - Maybe take some inspiration from MCStats.org ?
  - Stuff to stat (Global & per game, type, author(primary & all), gameversion)
    - nr of games
    - nr of addons
    - nr of files
    - nr of authors
    - Downloads
    - Filesizes
    - PopularityScores
    - GameVersions
    - Newest files
    - Newest addons
    - Newest authors (?)
    - Highest downloads 24h/7d/1m/
- Separate out UI and data
  - Now the analysis of the response gets triggered by the CurseClient module, but is processed in the Frontend module (as part of tasks)
  - Make a more modularized system (would also support better tests)
- File downloads (on the server)
  - This task must be locked!  (only 1 dl / analyze at the same time)
  - Get and store correct download URL
    - Store that instead of the original one, the original is always this:
      "https://files.forgecdn.net/files/${FILEID/1000}/${FILEID%1000}/${FILENAME}"
  - Get the filesize
  - Hash the file
    - SHA256 ?
  - Crazy idea: If it's a mod, analyze it, if it's a pack, parse the manifest?
- Archive
  - We are not in the business of archiving, but supporting others is OK.
  - Write a script people can use to keep an archive (preferably with options).
- Crazy idea: Draw a huge (interactive?) graph of the authors - addons relations + file dependencies?
- Write the history of CurseMeta somewhere, because it's interesting.
  - https://gist.github.com/dries007/10d8dc05a6fc5d1e700404cdd4446d21
- Write tests (meh)
  - Get a list of troubling addon/file ids to test on (weird characters, no files, etc)
- Pick a theme song.
  - Sonic X Theme Song ''Gotta Go Fast'' https://www.youtube.com/watch?v=yfGjLIPRgDA ?

**Comment by fiws** [comment]
My wishlist:

* Cached API (quick win: set Cache-Control and let Cloudflare do it) – The old api was soooooo much faster
* Addon -> LatestFiles -> Dependencies should always return an array, never null
* Provide full mod list as tar.xz again. I wanted to use them for a local db.. :(

**Comment by dries007** [comment]
- Caching is now done with Redis locally (1h) + Cloudflare (4h).
- Login tokens are now shared & cached (Redis) & is kept live at all times.
